ServicioTecnico/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('', include('ServicioTecnicoApps.urls')),
    path('registro/', include('registro.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
]

carro/urls.py
from django.urls import path 
from .import views 

app_name = 'carro'
urlpatterns = [

    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/<int:producto_id>/", views.limpiar_carro, name="limpiar"),

]

tienda/urls.py
from django.urls import path 
from .import views 

urlpatterns = [
    path('', views.tienda, name='Tienda'),
]

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from enum import auto
from django.db import models
from django.db.models.fields import DecimalField


class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Categoria Producto"
        verbose_name_plural = "Categorias Producto"

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProducto, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='tienda', null = True, blank = True)
    precio = models.IntegerField()
    disponible = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

carro/views.py
from django.shortcuts import render
from .carro import Carro
from tienda.models import Producto
from django.shortcuts import redirect

def agregar_producto(request,producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("Tienda")

def eliminar_producto(request,producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("Tienda")

def restar_producto(request,producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("Tienda")


def limpiar_carro(request,producto_id):
    carro = Carro(request)
    carro.limpiar_carro()
    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render, HttpResponse 
from .models import Producto



def tienda(request):
   productos = Producto.objects.all()
   return  render(request,"tienda/tienda.html", {"productos": productos})

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white;" style="display: block;">
    <thead>
        <tr>
            <th colspan="3" class = "text-center">
                <h4>CARRITO DE COMPRA</h4>
            </th>

        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Cantidad</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}">
                            <button class="btn btn-success" style="background-color: #2C3539;">
                                <span class="glyphicon glyphicon-plus">+</span>
                            </button>
                        </a>
                        <a href="{% url 'carro:restar' value.producto_id %}">
                            <button class="btn btn-danger" style="background-color: #2B3856;">
                                <span class="glyphicon glyphicon-minus">-</span>
                            </button>
                        </a>
                        {{value.precio}} CLP
                    </td>
                </tr>
            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        <strong>No hay productos en el carrito</strong>
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{ importe_total_carro }} CLP

            </td>


        </tr>
    </tfoot>

</table>